# Generated by Django 4.2.5 on 2023-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalImage', models.ImageField(upload_to='images/')),
                ('convertedImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
