# Generated by Django 5.0.1 on 2024-01-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_convertimage_convertedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertimage',
            name='convertedImage',
            field=models.FileField(upload_to='converted/'),
        ),
    ]
